loft_dev.settings:
  type: mapping
  label: Settings
  mapping:
    loft_dev_which_ld:
      type: string
    loft_dev_loft_deploy_export_path:
      type: string
    'loft_dev_parse_time:append_to_line':
      type: boolean
    'loft_dev_parse_time:append_prefix':
      type: string
    loft_dev_migration_canonical:
      type: string
    loft_dev_drupal_deploy_path:
      type: 'NULL'
    loft_dev_free_access:
      type: boolean
    loft_dev_playground_load_data:
      type: boolean
    loft_dev_loft_deploy_export_last:
      type: integer
    loft_dev_mail_capture:
      type: boolean
